#!/bin/sh

# Get user id
export USERID=`id -u`

# Check ROOT Permissions
if [ "$USERID" != 0 ]; then
echo "请以root用户运行"
exit 1
fi

# Check iptables
if ! command -v iptables > /dev/null 2>&1; then
echo "请安装iptables"
exit 1
fi

choose() {
echo "1.安装"
echo "2.卸载"
echo "3.退出"
read -p "请输入数字: " NUM
}

choose

if [ "$NUM" = 1 ]; then
read -p "Telegram代理使用的端口: " PORT

# Download
echo "下载中国大陆IP数据"
wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /tmp/cnip.txt

# Check download
if [ ! -f /tmp/cnip.txt ]; then
echo "下载失败,请检查网络"
fi

# iptables start
iptables -N CNONLY

iptables -I INPUT -p TCP --dport $PORT -j CNONLY
iptables -I INPUT -p UDP --dport $PORT -j CNONLY

iptables -A CNONLY -p TCP --dport $PORT -j DROP
iptables -A CNONLY -p UDP --dport $PORT -j DROP

for IP in `cat /tmp/cnip.txt`; do
iptables -A CNONLY -s $IP -p TCP --dport $PORT -j ACCEPT
iptables -A CNONLY -s $IP -p UDP --dport $PORT -j ACCEPT
done

echo "#!""/bin/sh" > /mnt/china_only
echo "export PORT=$PORT" >> /mnt/china_only
echo "wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /tmp/cnip.txt" >> /mnt/china_only
echo "iptables -F CNONLY" >> /mnt/china_only
echo "iptables -I INPUT -p TCP --dport $PORT -j CNONLY" >> /mnt/china_only
echo "iptables -I INPUT -p UDP --dport $PORT -j CNONLY" >> /mnt/china_only
echo "iptables -A CNONLY -p TCP --dport $PORT -j DROP" >> /mnt/china_only
echo "iptables -A CNONLY -p UDP --dport $PORT -j DROP" >> /mnt/china_only
echo "for IP in \`cat /tmp/cnip.txt\`; do" >> /mnt/china_only
echo "iptables -A CNONLY -s $IP -p TCP --dport $PORT -j ACCEPT" >> /mnt/china_only
echo "iptables -A CNONLY -s $IP -p UDP --dport $PORT -j ACCEPT" >> /mnt/china_only
echo "done" >> /mnt/china_only

if [ -f /var/spool/cron/crontabs/root ]; then
sed -i '/\/mnt\/china_only/d' /var/spool/cron/crontabs/root
fi

echo "@reboot sh /mnt/china_only >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
echo "0 0 * * * sh /mnt/china_only >/dev/null 2>&1" >> /var/spool/cron/crontabs/root
elif [ "$NUM" = 2 ]; then
rm -rf /mnt/china_only
sed -i '/\/mnt\/china_only/d' /var/spool/cron/crontabs/root
iptables -F CNONLY
elif [ "$NUM" = 3 ]; then
exit 0
else
choose
fi
