#!/bin/sh
# Block China Mobile,China Telecom,China Unicom and CNCERT attack server
cat >/etc/ip6tables.test.rules <<EOF
*filter
-I INPUT -s 2409:8880:3e01:200:100::/128 -j DROP
-I INPUT -s 240e:58:2:200:100::/128 -j DROP
-I INPUT -s 2408:8000:10fe:200:100::/128 -j DROP
-I INPUT -s 2001:da8:20b:200:100::/128 -j DROP
COMMIT
EOF

ip6tables-restore </etc/ip6tables.test.rules
ip6tables-save >/etc/ip6tables.up.rules

cat >/etc/network/if-pre-up.d/ip6tables <<EOF
#!/bin/sh
/sbin/ip6tables-restore < /etc/ip6tables.up.rules
EOF

chmod +x /etc/network/if-pre-up.d/ip6tables
