#!/bin/sh
cat >/etc/iptables.test.rules <<EOF
*filter
-A INPUT -p tcp -m tcp --dport 80 -j DROP
-A INPUT -p udp -m udp --dport 80 -j DROP
-A INPUT -p tcp -m tcp --dport 443 -j DROP
-A INPUT -p udp -m udp --dport 443 -j DROP
-A INPUT -p tcp -m tcp --dport 1723 -j DROP
-A INPUT -p udp -m udp --dport 1723 -j DROP
-A INPUT -p tcp -m tcp --dport 1701 -j DROP
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A INPUT -p tcp -m tcp --dport 500 -j DROP
-A INPUT -p udp -m udp --dport 500 -j DROP
-A INPUT -p tcp -m tcp --dport 4500 -j DROP
-A INPUT -p udp -m udp --dport 4500 -j DROP
-A INPUT -p tcp -m tcp --dport 1194 -j DROP
-A INPUT -p udp -m udp --dport 1194 -j DROP
-A INPUT -p tcp -m tcp --dport 3128 -j DROP
-A INPUT -p udp -m udp --dport 3128 -j DROP
COMMIT
EOF

iptables-restore </etc/iptables.test.rules
iptables-save >/etc/iptables.up.rules

cat >/etc/network/if-pre-up.d/iptables <<EOF
#!/bin/sh
/sbin/iptables-restore < /etc/iptables.up.rules
EOF

chmod +x /etc/network/if-pre-up.d/iptables

cat >>/etc/sysctl.conf <<EOF
net.ipv4.icmp_echo_ignore_all = 1
EOF

sysctl -p
