#!/bin/bash

read -p "Encryption(default:chacha20-ietf-poly1305): " encryption

if [ -z $encryption ]
then
encryption=chacha20-ietf-poly1305
fi

read -p "Run User(default:nobody): " run_user

if [ -z $run_user ]
then
run_user=nobody
fi

read -p "port$: " port
read -p "passwd: " passwd
ss-server -s 0.0.0.0 -p $port -k $passwd -m $encryption -a $run_user -u -d 8.8.8.8 --plugin obfs-server --plugin-opts "obfs=tls" -f /root/ss/shadowsocks-1.pid
