#!/bin/sh
export DEP=$PWD/dependencies
export USERID=`id -u`
export WORKDIRECTORY=$PWD/shadowsocks
export DEFAULTSHELL=`readlink -f /bin/sh`

encrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -i`
}

unencrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -d`
}

ss_config() {
. $WORKDIRECTORY/ss_config
}

run_server() {
. $WORKDIRECTORY/run
}

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "创建工作目录"
else
  echo "Create work directory"
fi

if [ -d "$WORKDIRECTORY" ]; then
  rm -rf $WORKDIRECTORY
fi
mkdir $WORKDIRECTORY
echo "export WORKDIRECTORY=$WORKDIRECTORY" >> $WORKDIRECTORY/envsetup.sh

# Check ROOT Permissions
if [ "$USERID" != 0 ] && [ -f /etc/sudoers ]; then
  unset SUDO
  export SUDO=yes
if [ $LANG=zh_CN.UTF-8 ]; then
if [ $DEFAULTSHELL = $DEFAULTSHELL ]; then
  read -p "请输入当前用户密码: " PASSWD
else
  read -s -p "请输入当前用户密码: " PASSWD
fi
else
if [ $DEFAULTSHELL = $DEFAULTSHELL ]; then
  read -p "Please enter the current user password: " PASSWD
else
  read -s -p "Please enter the current user password: " PASSWD
fi
fi
encrytedpasswd
echo "export PASSWD=$PASSWD" >> $WORKDIRECTORY/envsetup.sh
else if [ "$USERID" = 0 ]; then
  unset SUDO
  export SUDO=no
else if [ $LANG=zh_CN.UTF-8 ]; then
  echo "你没有root权限,请尝试安装sudo或者切换至root用户"
  exit 1
else
  echo "You don't have root permissions,please try install sudo or change to root user"
  exit 1
fi
fi
fi
unset USERID
echo "export SUDO=$SUDO" >> $WORKDIRECTORY/envsetup.sh

# Check memsize
MEM_CHECK=`cat /proc/meminfo | grep MemTotal | grep '[0-9]' -o | awk BEGIN{RS=EOF}'{gsub(/\n/,"");print}'`
# Preclude out of memory
if [ "$MEM_CHECK" -ge "524288" ]; then
  export CPU_NUM=`cat /proc/cpuinfo | grep processor | wc -l`
else
  export CPU_NUM=1
fi
echo "export CPU_NUM=$CPU_NUM" >> $WORKDIRECTORY/envsetup.sh
chmod +x $WORKDIRECTORY/envsetup.sh

# Check linux distribution
#Debian Base
if [ -f /etc/debian_version ]; then
DEBIAN_VERSION=`cat /etc/debian_version`

case "$DEBIAN_VERSION" in
  7|7.0|7.1|7.2|7.3|7.4|7.5|7.6|7.7|7.8|7.9|7.10|7.11)
    . $DEP/debian-7
  ;;
  8|8.0|8.1|8.2|8.3|8.4|8.5|8.6|8.7|8.8|8.9|8.10|jessie/sid)
    . $DEP/debian-8
  ;;
  9|9.0|9.1|9.2|9.3|9.4|stretch/sid)
    . $DEP/debian-9
  ;;
  buster/sid)
    . $DEP/debian-sid
esac

fi

#Redhat Base
if [ -f /etc/redhat-release ]; then
REDHAT_VERSION=`cat /etc/redhat-release | grep -oE  "[0-9.]+"`

case "$REDHAT_VERSION" in
  7.0.1406|7.1.1503|7.2.1511|7.3.1611|7.4.1708)
    . $DEP/redhat7
  ;;
  6.0|6.1|6.2|6.3|6.4|6.5|6.6|6.7|6.8|6.9)
    . $DEP/redhat6
  ;;
  *)
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "暂不支持您的系统"
  exit 1
else
  echo "Does not support your open system"
  exit 1
fi
esac

fi

export KERNEL_VERSION=`uname -r`
if [ $SUDO = yes ]; then
unencrytedpasswd
export VM=`echo $PASSWD | sudo -S virt-what`
encrytedpasswd
elif [ $SUDO = no ]; then
export VM=`virt-what`
fi

. $DEP/bbr

#Autoupdate requirement check
if [ "$AUTOUPDATE_CHECK" = "yes" ] || [ "$AUTOUPDATE_CHECK" = "" ]; then
if [ $LANG=zh_CN.UTF-8 ]; then
  read -p "是否部署自动更新?(yes/no) (default:yes): " AUTOUPDATE_CHECK
else
  read -p "Whether to deploy automatic updates?(yes/no) (default:yes): " AUTOUPDATE_CHECK
fi
if [ "$AUTOUPDATE_CHECK" = "yes" ] || [ "$AUTOUPDATE_CHECK" = "" ]; then
  cp -v $DEP/ss_update $WORKDIRECTORY
  cp -v $DEP/libsodium_update $WORKDIRECTORY
  cp -v $DEP/mbedtls_update $WORKDIRECTORY
  cp -v $DEP/shadowsocks_update $WORKDIRECTORY
  cp -v $DEP/simple-obfs_update $WORKDIRECTORY
  echo "0 0 * * * `whoami` sh $WORKDIRECTORY/ss_update" > $WORKDIRECTORY/`whoami`
if [ $SUDO = yes ]; then
  unencrytedpasswd
  echo $PASSWD | sudo -S cat $WORKDIRECTORY/`whoami` >> /var/spool/cron/crontabs/`whoami`
  encrytedpasswd
elif [ $SUDO = no ]; then
  cat $WORKDIRECTORY/`whoami` >> /var/spool/cron/crontabs/`whoami`
fi
fi
fi

cp -v $DEP/ss_config $WORKDIRECTORY
ss_config

if [ $LANG=zh_CN.UTF-8 ]; then
  read -p "是否运行Shadowsocks服务器?" RUN_SERVER
else
  read -p "Running shadowsocks server?" RUN_SERVER
fi
  cp -v $DEP/run $WORKDIRECTORY
if [ $RUN_SERVER = yes ]; then
run_server
fi

unset MEM_CHECK
unset CPU_NUM
unset DEBIAN_VERSION
unset REDHAT_VERSION
unset WORKDIRECTORY
unset DEFAULTSHELL
