#!/bin/sh
#Install
curl https://get.acme.sh | sh
. ~/.acme.sh/acme.sh.env

HTTP_CHECK=$(lsof -i:80)
if [ "$HTTP_CHECK" != "" ]; then
  if [ "$LANG" = "zh_CN.UTF-8" ]; then
    echo "80端口被占用无法使用此方式生成证书"
  else
    echo "80 port is occupied. Can't be used this method to generate a certificate."
  fi
  if [ "$LANG" = "zh_CN.UTF-8" ]; then
    read -p "您是否使用或安装了Apche2/Nginx服务器?如果是,请确保您没有对80端口进行强制https跳转.如果没有,请检查占用80端口的程序. (no/apache2/nginx)" WEB_SERVER
  else
    read -p "Are you using or installing the Apche2/Nginx server? If so, make sure you don't force a https jump on port 80. If not, check the program that occupies port 80. (no/apache2/nginx)" WEB_SERVER
  fi
else
  if [ "$LANG" = "zh_CN.UTF-8" ]; then
    read -p "是否通过 IPv6 完成域名认证？这适用于使用共享 IPv4 地址但有独立 IPv6 地址的用户。(yes/no) [yes]：" ACMESH_IPv6
  else
    read -p "Do you want to validate domain over IPv6? This is useful to users using shared IPv4 address but with dedicated IPv6 address available to them. (yes/no) [yes]: " ACMESH_IPv6
  fi
  if [ "$ACMESH_IPv6" = "yes" ] || [ "$ACMESH_IPv6" = "" ]; then
    ACMESH_IPv6=--listen-v6
  elif [ "$ACMESH_IPv6" = "no" ]; then
    ACMESH_IPv6=
  fi
  acme.sh --issue -d $HOSTNAME --standalone $ACMESH_IPv6
fi

if [ "$WEB_SERVER" = "no" ]; then
  . $DEP/ss_config
elif [ "$WEB_SERVER" = "apache2" ]; then
  acme.sh --issue -d $HOSTNAME --apache
elif [ "$WEB_SERVER" = "nginx" ]; then
  acme.sh --issue -d $HOSTNAME --nginx
fi

unset HTTP_CHECK
unset ACMESH_IPv6
unset WEB_SERVER
