#!/bin/sh
#Update autoconf to 2.69 for Redhat 6 derivatives
echo "$MSG_AUTOCONF"

if [ "$SUDO" = "yes" ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE yum install curl tar openssl-devel -y
  $ENCRYTEDPASSWD
elif [ "$SUDO" = "no" ]; then
  yum install curl tar openssl-devel -y
fi

curl -L -O http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar zxf autoconf-2.69.tar.gz
cd autoconf-2.69
./configure --prefix=$WORKDIRECTORY
make -j$CPU_NUM
make install
export PATH=$WORKDIRECTORY/bin:$PATH
cd ..
