#!/bin/sh
#BBR Check
if [ "$(cat /proc/sys/net/ipv4/tcp_congestion_control)" = "bbr" ]; then
  echo "$MSG_BBRLOAD"
else
  sysctl_config
  if [ -n "$(find /lib/modules/$(uname -r)/kernel/net/ipv4 -name 'tcp_bbr.ko*' -print -quit)" ]; then
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      echo $PASSWD | sudo -SE modprobe tcp_bbr
      echo $PASSWD | sudo -SE sh -c "echo 'tcp_bbr' >> /etc/modules-load.d/modules.conf"
      echo $PASSWD | sudo -SE sh -c "echo 'net.core.default_qdisc=fq' >> ${FILE}"
      echo $PASSWD | sudo -SE sh -c "echo 'net.ipv4.tcp_congestion_control=bbr' >> ${FILE}"
      echo $PASSWD | sudo -SE sysctl --system
    fi
      $ENCRYTEDPASSWD
  elif [ "$SUDO" = "no" ]; then
      modprobe tcp_bbr
      echo 'tcp_bbr' >>/etc/modules-load.d/modules.conf
      echo 'net.core.default_qdisc=fq' >>${FILE}
      echo 'net.ipv4.tcp_congestion_control=bbr' >>${FILE}
      sysctl --system
  fi
  echo "$MSG_BBRENABLE"
fi
