#!/bin/sh
if [ -f "$PWD/envsetup.sh" ]; then
  . $PWD/envsetup.sh
else
  exit 1
fi

for PIDFILE in $WORKDIRECTORY/pid/shadowsocks-*.pid; do
  PIDNUM=$(cat $PIDFILE)
  if [ ! -d /proc/$PIDNUM ]; then
    PID_NUM=$(echo $PIDFILE | grep -oE "[0-9]")
    . bin/run
  fi
done
