#!/bin/bash
source debian
echo "Enabled BBR"
bbr_check=`lsmod | grep bbr`
if [ -z "$bbr_check" ]
then
modprobe tcp_bbr
echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
fi
