#!/bin/sh
# Update system
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "更新系统"
else
  echo "Update system"
fi
$SUDO apt-get update && $SUDO apt-get upgrade -y

# Installation of basic build dependencies
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译时需要的依赖包"
else
  echo "Installation of basic build dependencies"
fi
$SUDO apt-get install --no-install-recommends gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev automake asciidoc xmlto git libc-ares-dev git -y

# Install virtual machine architecture check package
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装虚拟机架构检测包"
else
  echo "Install virtual machine architecture check package"
fi
$SUDO apt-get install virt-what -y

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "新建~/shadowsocks目录"
else
  echo "mkdir ~/shadowsocks directory"
fi

mkdir ~/shadowsocks

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "进入~/shadowsocks"
else
  echo "work in ~/shadowsocks"
fi

cd ~/shadowsocks

. $DEP/libsodium
. $DEP/mbedtls
. $DEP/shadowsocks
. $DEP/simple-obfs
