#!/bin/sh
#Check device driver
KERNEL_DRIVER=$(ls /lib/modules/$KERNEL_VERSION/kernel/drivers -R | sed '/^\./d' | sed '/\//d' | sed '/^$/d')
for driver in $KERNEL_DRIVER; do
  echo $driver >>/tmp/driver_check
done
