#!/bin/sh
#Install kcptun
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装kcptun插件"
else
  echo "Install kcptun plugin"
fi

if [ "$GOLANG_WORK" = "yes" ]; then
if [ ! -d kcptun ]; then
mkdir kcptun
fi
cd kcptun
go get -u github.com/shadowsocks/kcptun/server
go build github.com/shadowsocks/kcptun/server
mv server $WORKDIRECTORY/bin/kcptun-server
KCPTUN_INSTALL=yes
else
KCPTUN_INSTALL=no
fi

echo "export KCPTUN_INSTALL=$KCPTUN_INSTALL" >>$WORKDIRECTORY/envsetup.sh

if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/kcptun-server
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/kcptun-server
fi

cd ..
