#!/bin/sh
#Install Need Dep
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译内核时需要的依赖包"
else
  echo "Installation of kernel basic build dependencies"
fi
if [ $OS = debian ]; then
  echo $PASSWD | sudo -SE apt-get install build-essential bison flex libelf-dev libssl-dev libncurses5-dev bc -y
else
  if [ $OS = redhat6 ] || [ $OS = redhat7 ]; then
    echo $PASSWD | sudo -SE yum groupinstall "Development Tools" -y
    echo $PASSWD | sudo -SE yum install openssl-devel bc flex bison -y
  fi
fi

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "下载Linux内核源码"
else
  echo "Dowload Linux kernel Source"
fi
git clone --depth 1 https://github.com/torvalds/linux.git
cd linux
yes "" | make oldconfig
echo "CONFIG_TCP_CONG_BBR=y" >>.config
echo "CONFIG_DEFAULT_BBR=y" >>.config
make
make modules
echo $PASSWD | sudo -SE make modules_install
echo $PASSWD | sudo -SE make install
cd ..

#Enable BBR
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "开启BBR"
else
  echo "BBR ENABLED"
fi
echo $PASSWD | sudo -SE echo "tcp_bbr" >>/etc/modules-load.d/modules.conf
echo $PASSWD | sudo -SE echo "net.core.default_qdisc=fq" >>/etc/sysctl.conf
echo $PASSWD | sudo -SE echo "net.ipv4.tcp_congestion_control=bbr" >>/etc/sysctl.conf

unset VM
