#!/bin/sh
echo "Install Need Dep"
$SUDO apt-get build-dep linux-image-$(uname -r)
$SUDO apt-get install git

echo "Dowload Linux kernel Source"
git clone https://github.com/torvalds/linux.git
cd linux
make localmodconfig
echo "CONFIG_TCP_CONG_BBR=y" >> .config
echo "CONFIG_DEFAULT_BBR=y" >> .config
make -j$CPU_NUM
make -j$CPU_NUM modules
$SUDO make install
$SUDO make modules_install
cd ..