#!/bin/sh
#Building libev
echo "$MSG_LIBEV"

curl -L -O http://dist.schmorp.de/libev/libev-4.33.tar.gz
tar zxf libev-4.33.tar.gz
cd libev-4.33
./configure --prefix=$WORKDIRECTORY --disable-shared
make -j$CPU_NUM
make install
cd ..
