#!/bin/sh
#Update Libsodium
cd libsodium
make distclean
git fetch
git reset --hard origin/master
./autogen.sh
./configure --prefix=$WORKDIRECTORY --disable-shared && make -j$CPU_NUM
make install
cd ..
