#!/bin/sh
#Installation of Libsodium
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装Libsodium"
else
  echo "Installation of Libsodium"
fi

git clone https://github.com/jedisct1/libsodium.git
cd libsodium 
./autogen.sh
./configure --prefix=/usr && make -j$CPU_NUM
if [ $SUDO = yes ]; then
echo $PASSWD | sudo -S make install
echo $PASSWD | sudo -S ldconfig
elif [ $SUDO = no ]; then
make install
ldconfig
fi
cd ..
