#!/bin/sh
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装MbedTLS"
else
  echo "Installation of MbedTLS"
fi

git clone https://github.com/ARMmbed/mbedtls.git
cd mbedtls
make SHARED=1 CFLAGS=-fPIC -j$CPU_NUM
if [ $SUDO = yes ]; then
echo $PASSWD | sudo -S make DESTDIR=/usr install
echo $PASSWD | sudo -S ldconfig
elif [ $SUDO = no ]; then
make DESTDIR=/usr install
ldconfig
fi
cd ..
