#!/bin/sh
if [ "$LANG" = "zh_CN.UTF-8" ]; then
  echo "在$WORKDIRECTORY安装MbedTLS"
else
  echo "Installation MbedTLS in $WORKDIRECTORY"
fi

git clone --recursive https://github.com/ARMmbed/mbedtls.git
cd mbedtls
make SHARED=1 CFLAGS=-fPIC -j$CPU_NUM
make DESTDIR=$WORKDIRECTORY install
cd ..
