#!/bin/sh
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装MbedTLS"
else
  echo "Installation of MbedTLS"
fi

git clone https://github.com/ARMmbed/mbedtls.git
cd mbedtls
make SHARED=1 CFLAGS=-fPIC -j$CPU_NUM
$SUDO make DESTDIR=/usr install
cd ..
$SUDO ldconfig
