#!/bin/sh
encrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -i`
}

unencrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -d`
}

export OS=redhat6
echo "export OS=$OS" >> $WORKDIRECTORY/envsetup.sh

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "进入$WORKDIRECTORY/src"
else
  echo "work in $WORKDIRECTORY/src"
fi

cd $WORKDIRECTORY/src

# Update system
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "更新系统"
else
  echo "Update system"
fi
if [ $SUDO = yes ]; then
echo $PASSWD | sudo -SE yum update -y
elif [ $SUDO = no ]; then
yum update -y
fi

#Install Redhat 6 and its derivative building dependencies
. $DEP/autoconf
. $DEP/libev
. $DEP/redhat
