#!/bin/sh
export OS=redhat7
echo "export OS=$OS" >>$WORKDIRECTORY/envsetup.sh

echo "$MSG_WORKDIR"
cd $WORKDIRECTORY/src

# Update system
echo "$MSG_UPPACK"
if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE yum update -y
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  yum update -y
fi

. $DEP/redhat

if [ "$SUDO" = "yes" ]; then
  $UNENCRYTEDPASSWD
  sudo systemctl enable cron
  $ENCRYTEDPASSWD
elif [ "$SUDO" = "no" ]; then
  systemctl enable cron
fi
