#!/bin/sh
export OS=redhat6
echo "export OS=$OS" >>$WORKDIRECTORY/envsetup.sh

echo "$MSG_WORKDIR"

cd $WORKDIRECTORY/src

# Update system
echo "$MSG_UPPACK"
if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE yum update -y
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  yum update -y
fi

#Install Redhat 6 and its derivative building dependencies
. $DEP/autoconf
. $DEP/redhat
if [ "$SUDO" = "yes" ]; then
  $UNENCRYTEDPASSWD
  sudo chkconfig crond on
  $ENCRYTEDPASSWD
elif [ "$SUDO" = "no" ]; then
  chkconfig crond on
fi
