#!/bin/sh
export OS=redhat7

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "进入$WORKDIRECTORY"
else
  echo "work in $WORKDIRECTORY"
fi

cd $WORKDIRECTORY

# Update system
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "更新系统"
else
  echo "Update system"
fi
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S yum update -y
encrytedpasswd
elif [ $SUDO = no ]; then
yum update -y
fi

# Installation of basic build dependencies(Redhat 7)
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译Shadowsocks-libev时需要的依赖包(Redhat 7)"
else
  echo "Installation of basic Shadowsocks-libev build dependencies(Redhat 7)"
fi
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S yum install autoconf libev-devel -y
encrytedpasswd
elif [ $SUDO = no ]; then
yum install autoconf libev-devel -y
fi

. $DEP/redhat
