#!/bin/sh
# Installation of basic build dependencies
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译Shadowsocks-libev时需要的依赖包"
else
  echo "Installation of basic Shadowsocks-libev build dependencies"
fi
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel pcre-devel curl git -y
encrytedpasswd
elif [ $SUDO = no ]; then
yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel pcre-devel curl git -y
fi

# Install virtual machine architecture check package
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装虚拟机架构检测包"
else
  echo "Install virtual machine architecture check package"
fi
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S yum install virt-what which -y
encrytedpasswd
elif [ $SUDO = no ]; then
yum install virt-what which -y
fi

. $DEP/libsodium
. $DEP/mbedtls
. $DEP/shadowsocks
. $DEP/simple-obfs
