#!/bin/bash
# Update system
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "更新系统"
else
  echo "Update system"
fi

$SUDO yum update -a

# Installation of basic build dependencies
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译时需要的依赖包"
else
  echo "Installation of basic build dependencies"
fi

$SUDO yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel libev-devel git -y

# Install virtual machine architecture check package
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装虚拟机架构检测包"
else
  echo "Install virtual machine architecture check package"
fi
$SUDO yum install virt-what -y

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "新建~/shadowsocks目录"
else
  echo "mkdir ~/shadowsocks directory"
fi

mkdir ~/shadowsocks

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "进入~/shadowsocks"
else
  echo "work in ~/shadowsocks"
fi

cd ~/shadowsocks

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装Libsodium"
else
  echo "Installation of Libsodium"
fi

git clone https://github.com/jedisct1/libsodium.git
pushd libsodium 
./autogen.sh
./configure --prefix=/usr && make -j$cpu_num
$SUDO make install
popd
$SUDO ldconfig

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装MbedTLS"
else
  echo "Installation of MbedTLS"
fi

git clone https://github.com/ARMmbed/mbedtls.git
pushd mbedtls
make SHARED=1 CFLAGS=-fPIC -j$cpu_num
$SUDO make DESTDIR=/usr install
popd
$SUDO ldconfig

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装Shadowsocks-libev"
else
  echo "Installation of Shadowsocks-libev"
fi

git clone https://github.com/shadowsocks/shadowsocks-libev.git
pushd shadowsocks-libev
git submodule update --init --recursive
./autogen.sh && ./configure && make -j$cpu_num
$SUDO make install
popd

if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装simple-obfs"
else
  echo "Install simple-obfs"
fi

git clone https://github.com/shadowsocks/simple-obfs.git
pushd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make -j$cpu_num
$SUDO make install
popd
