#!/bin/sh
export OS=redhat6
#Install Redhat 6 and its derivative building dependencies
# Installation of basic build dependencies
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装编译Shadowsocks-libev时需要的依赖包"
else
  echo "Installation of basic Shadowsocks-libev build dependencies"
fi
if [ $SUDO = yes ]; then
echo $PASSWD | sudo -S yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel pcre-devel curl git -y
elif [ $SUDO = no ]; then
yum install gettext gcc autoconf libtool automake make asciidoc xmlto c-ares-devel pcre-devel curl git -y
fi

. $DEP/autoconf
. $DEP/libev
. $DEP/redhat

#Auto uninstall autoconf after the script is completed
if [ "$UNINSTALL_AUTOCONF" = "yes" ]; then
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "卸载autoconf 2.69"
else
  echo "uninstall autoconf 2.69"
fi

cd autoconf-2.69
if [ $SUDO = yes ]; then
echo $PASSWD | sudo -S make uninstall
elif [ $SUDO = no ]; then
make uninstall
fi
elif [ "$UNINSTALL_AUTOCONF" = "no" ] || [ "$UNINSTALL_AUTOCONF" = "" ]; then
export AUTOUPDATE_CHECK=yes
fi
