#!/bin/sh
if [ -f "$PWD/envsetup.sh" ]; then
./envsetup.sh
else
exit 1
fi

encrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -i`
}

unencrytedpasswd() {
export PASSWD=`echo "$PASSWD" | base64 -d`
}

if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S sh -c $WORKDIRECTORY/ss_run
encrytedpasswd
elif [ $SUDO = no ]; then
sh $WORKDIRECTORY/ss_run
fi
