#!/bin/sh
#Installation of Shadowsocks-libev
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装Shadowsocks-libev"
else
  echo "Installation of Shadowsocks-libev"
fi

git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd shadowsocks-libev
git submodule update --init --recursive
./autogen.sh && ./configure && make -j$CPU_NUM
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S make install
encrytedpasswd
elif [ $SUDO = no ]; then
make install
fi
cd ..
