#!/bin/sh
#Shadowsocks-libev static
echo "$MSG_SS"

if [ -z "$SS_URL" ]; then
  git clone --recursive https://github.com/shadowsocks/shadowsocks-libev.git
else
  git clone --recursive $SS_URL
fi

cd shadowsocks-libev
mkdir -p build && cd build
cmake .. -DCMAKE_PREFIX_PATH="${WORKDIRECTORY}" -DCMAKE_BUILD_TYPE=Release -DWITH_SHARED=OFF -DWITH_STATIC=ON -DENABLE_CONNMARKTOS=ON -DENABLE_NFTABLES=ON && make -j$CPU_NUM
mv bin/ss-server ${WORKDIRECTORY}/bin/ss-server

if [ "$SUDO" = "yes" ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
  $ENCRYTEDPASSWD
elif [ "$SUDO" = "no" ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
fi

cd ..
