#!/bin/sh
#Update Shadowsocks-libev
cd shadowsocks-libev
make distclean
git pull
git submodule update --init --recursive
if [ "$OS" = "redhat6" ]; then
./autogen.sh && ./configure --with-mbedtls=$WORKDIRECTORY --with-sodium=$WORKDIRECTORY --with-ev=$WORKDIRECTORY --prefix=$WORKDIRECTORY && make -j$CPU_NUM
else
./autogen.sh && ./configure --with-mbedtls=$WORKDIRECTORY --with-sodium=$WORKDIRECTORY --prefix=$WORKDIRECTORY && make -j$CPU_NUM
fi

make install

if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
encrytedpasswd
elif [ $SUDO = no ]; then
setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
fi
cd ..
