#!/bin/sh
#Update Shadowsocks-libev static
cd shadowsocks-libev
rm -rf build
git fetch
git reset --hard origin/master
git submodule update --init --recursive
mkdir -p build && cd build
cmake .. -DCMAKE_PREFIX_PATH="${WORKDIRECTORY}" -DCMAKE_INSTALL_PREFIX="${WORKDIRECTORY}" -DCMAKE_BUILD_TYPE=Release -DWITH_SHARED=OFF -DWITH_STATIC=ON -DENABLE_CONNMARKTOS=ON -DENABLE_NFTABLES=ON && make -j$CPU_NUM
make install

if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/ss-server
fi

cd ..
