#!/bin/sh
#Install simple-obfs
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装simple-obfs插件"
else
  echo "Install simple-obfs plugin"
fi

git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
if [ "$OS" = "redhat6" ]; then
  ./configure --with-ev=$WORKDIRECTORY --prefix=$WORKDIRECTORY && make -j$CPU_NUM
else
  ./configure --prefix=$WORKDIRECTORY && make -j$CPU_NUM
fi

make install

if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/obfs-server
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/obfs-server
fi

cd ..
