#!/bin/sh
#Install simple-obfs
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装simple-obfs"
else
  echo "Install simple-obfs"
fi

git clone https://github.com/shadowsocks/simple-obfs.git
cd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make -j$CPU_NUM
if [ $SUDO = yes ]; then
unencrytedpasswd
echo $PASSWD | sudo -S make install
encrytedpasswd
elif [ $SUDO = no ]; then
make install
fi
cd ..
