#!/bin/sh
#Install simple-obfs
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装simple-obfs"
else
  echo "Install simple-obfs"
fi

git clone https://github.com/shadowsocks/simple-obfs.git
pushd simple-obfs
git submodule update --init --recursive
./autogen.sh
./configure && make -j$cpu_num
$SUDO make install
popd
