#!/bin/sh
encrytedpasswd() {
  export PASSWD=$(echo "$PASSWD" | base64 -i)
}

unencrytedpasswd() {
  export PASSWD=$(echo "$PASSWD" | base64 -d)
}

if [ -f "$PWD/envsetup.sh" ]; then
  . $PWD/envsetup.sh
else
  exit 1
fi

if [ ! -d "$WORKDIRECTORY/pid" ]; then
  mkdir -v $WORKDIRECTORY/pid
fi

if [ ! -d "$WORKDIRECTORY/config" ]; then
  mkdir -v $WORKDIRECTORY/config
fi

#TCP fast open check
if [ -f "/proc/sys/net/ipv4/tcp_fastopen" ]; then
  FASTOPEN_CHECK=$(cat /proc/sys/net/ipv4/tcp_fastopen)
  if [ "$FASTOPEN_CHECK" = 3 ]; then
    FASTOPEN=--fast-open
  else
    FASTOPEN=
  fi
else
  echo "$MSG_SS_TFO"
fi

read -p "$MSG_SS_ENCRYPTION" ENCRYPTION

if [ -z $ENCRYPTION ]; then
  ENCRYPTION=chacha20-ietf-poly1305
fi

read -p "$MSG_SS_USER" RUN_USER

if [ -z $RUN_USER ]; then
  RUN_USER=nobody
fi

read -p "$MSG_SS_UDP" UDP

if [ "$UDP" = "yes" ] || [ "$UDP" = "" ]; then
  UDP=-u
elif [ "$UDP" = "no" ]; then
  UDP=
fi

read -p "$MSG_SS_NODELAY" TCP_NODELAY

if [ "$TCP_NODELAY" = "yes" ] || [ "$TCP_NODELAY" = "" ]; then
  TCP_NODELAY=--no-delay
elif [ "$TCP_NODELAY" = "no" ]; then
  TCP_NODELAY=
fi

read -p "$MSG_SS_PORT_REUSE" PORT_REUSE

if [ "$PORT_REUSE" = "yes" ] || [ "$PORT_REUSE" = "" ]; then
  PORT_REUSE=--reuse-port
elif [ "$PORT_REUSE" = "no" ]; then
  PORT_REUSE=
fi

port_check() {
  read -p "port: " PORT

  if [ "$PORT" = "" ]; then
    port_check
  else
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      PORT_USE_CHECK=$(echo $PASSWD | sudo -SE sh -c "lsof -i:$PORT")
      $ENCRYTEDPASSWD
    elif [ "$SUDO" = "no" ]; then
      PORT_USE_CHECK=$(lsof -i:$PORT)
    fi
    if [ "$PORT_USE_CHECK" != "" ] || [ "$PORT" = "" ]; then
      port_check
    else
      if [ -f "$WORKDIRECTORY/config/ss_run1" ]; then
        PORT_EXIST=$(grep -rwo "\-p $PORT" $WORKDIRECTORY/config)
        PID_NUM=$(grep -ro 'ss-server' $WORKDIRECTORY/config | wc -l)
        PID_NUM=$(expr $PID_NUM + 1)
      else
        PORT_EXIST=""
        PID_NUM=1
        FIRST_RUN=yes
      fi
      if [ "$PORT_EXIST" != "" ]; then
        port_check
      else
        if [ "$PORT" -lt 8300 ] || [ "$PORT" -gt 8400 ]; then
          read -p "passwd: " PASSWORD

          if ip -6 addr show scope global | grep -q 'inet6'; then
            echo "#!""/bin/sh" >>$WORKDIRECTORY/config/ss_run$PID_NUM
            echo "ss-server -s 0.0.0.0 -s :: -p $PORT -k $PASSWORD -m $ENCRYPTION -a $RUN_USER $UDP -6 $TCP_NODELAY $FASTOPEN $PORT_REUSE -f $WORKDIRECTORY/pid/shadowsocks-$PID_NUM.pid" >>$WORKDIRECTORY/config/ss_run$PID_NUM
          else
            echo "#!""/bin/sh" >>$WORKDIRECTORY/config/ss_run$PID_NUM
            echo "ss-server -s 0.0.0.0 -p $PORT -k $PASSWORD -m $ENCRYPTION -a $RUN_USER $UDP $TCP_NODELAY $FASTOPEN $PORT_REUSE -f $WORKDIRECTORY/pid/shadowsocks-$PID_NUM.pid" >>$WORKDIRECTORY/config/ss_run$PID_NUM
          fi
        else
          echo "$MSG_SS_PORT_RANGE"
          port_check
        fi
      fi
    fi
  fi

  if [ "$OS" = "redhat7" ]; then
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      echo $PASSWD | sudo -SE firewall-cmd --permanent --zone=public --add-port=$PORT/udp
      echo $PASSWD | sudo -SE firewall-cmd --permanent --zone=public --add-port=$PORT/tcp
      echo $PASSWD | sudo -SE firewall-cmd --reload
      $ENCRYTEDPASSWD
    elif [ "$SUDO" = "no" ] || [ "$SUDO" = "" ]; then
      firewall-cmd --permanent --zone=public --add-port=$PORT/udp
      firewall-cmd --permanent --zone=public --add-port=$PORT/tcp
      firewall-cmd --reload
    fi
  elif [ "$OS" = "redhat6" ]; then
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      echo $PASSWD | sudo -SE iptables -I INPUT -p tcp --dport $PORT -j ACCEPT
      echo $PASSWD | sudo -SE iptables -I INPUT -p udp --dport $PORT -j ACCEPT
      echo $PASSWD | sudo -SE service iptables save
      $ENCRYTEDPASSWD
    elif [ "$SUDO" = "no" ] || [ "$SUDO" = "" ]; then
      iptables -I INPUT -p tcp --dport $PORT -j ACCEPT
      iptables -I INPUT -p udp --dport $PORT -j ACCEPT
      service iptables save
    fi
  fi
}

port_check

read -p "$MSG_SS_START" RUN_SERVER

if [ "$FIRST_RUN" = "yes" ]; then
  ln -vf $DEP/run $WORKDIRECTORY/bin/run
fi
if [ "$RUN_SERVER" = "yes" ] || [ "$RUN_SERVER" = "" ]; then
  . $WORKDIRECTORY/bin/run
fi

unset ENCRYPTION
unset PORT
unset PASSWD
unset PASSWORD
unset FASTOPEN
unset UDP
unset TCP_NODELAY
unset FASTOPEN_CHECK
unset PORT_EXIST
unset PORT_USE_CHECK
unset RUN_SERVER
