#!/bin/sh
if [ -f "$PWD/envsetup.sh" ]; then
  . $PWD/envsetup.sh
else
  exit 1
fi

encrytedpasswd() {
  export PASSWD=$(echo "$PASSWD" | base64 -i)
}

unencrytedpasswd() {
  export PASSWD=$(echo "$PASSWD" | base64 -d)
}

for SSRUN in $WORKDIRECTORY/config/ss_run*; do
  if [ -f $SSRUN -a $SSRUN ]; then
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      echo $PASSWD | sudo -SE env "PATH=$WORKDIRECTORY/bin:$PATH" sh $SSRUN
      $ENCRYTEDPASSWD
    elif [ "$SUDO" = "no" ]; then
      sh $SSRUN
    fi
  fi
done
