#!/bin/sh
#fastopen_check
if [ $(cat /proc/sys/net/ipv4/tcp_fastopen) = 3 ]; then
  echo "$MSG_TFOLOAD"
else
  sysctl_config
  if [ -f "/proc/sys/net/ipv4/tcp_fastopen" ]; then
    if [ "$SUDO" = "yes" ]; then
      $UNENCRYTEDPASSWD
      echo $PASSWD | sudo -SE sh -c "echo 'net.ipv4.tcp_fastopen = 3' >> $FILE"
      echo $PASSWD | sudo -SE sysctl --system
      $ENCRYTEDPASSWD
	elif [ "$SUDO" = "no" ]; then
      echo 'net.ipv4.tcp_fastopen = 3' >> $FILE
      sysctl --system
    fi
    echo "$MSG_TFOENABLE"
  fi
fi
