#!/bin/sh
#Install v2ray-plugin
if [ $LANG=zh_CN.UTF-8 ]; then
  echo "安装基于v2ray的插件"
else
  echo "Install v2ray based plugin"
fi

if [ "$GOLANG_WORK" = "yes" ]; then
git clone https://github.com/shadowsocks/v2ray-plugin.git
cd v2ray-plugin
go build -ldflags "-s -w"
upx -9 v2ray-plugin
mv v2ray-plugin $WORKDIRECTORY/bin/v2ray-plugin
V2RAY_PLUGIN_INSTALL=yes
else
V2RAY_PLUGIN_INSTALL=no
fi

echo "export V2RAY_PLUGIN_INSTALL=$V2RAY_PLUGIN_INSTALL" >>$WORKDIRECTORY/envsetup.sh

if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/v2ray-plugin
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/v2ray-plugin
fi

cd ../..
