#!/bin/sh
#Update v2ray-plugin

if [ "$V2RAY_PLUGIN_INSTALL" = "yes" ]; then
cd v2ray-plugin
git pull
go get
go build
mv v2ray-plugin $WORKDIRECTORY/bin/v2ray-plugin
fi

if [ $SUDO = yes ]; then
  $UNENCRYTEDPASSWD
  echo $PASSWD | sudo -SE setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/v2ray-plugin
  $ENCRYTEDPASSWD
elif [ $SUDO = no ]; then
  setcap cap_net_bind_service+ep $WORKDIRECTORY/bin/v2ray-plugin
fi

cd ..
